### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by orenavram** [berkindurmus/SLIViT#4]
(slivit) mock@halperingpu01:/scratch/mock/projects/SLIViT$ python bb_train.py --dataset kermany --data_dir /scratch/mock/datasets/OCT2017/ --meta_csv Dsets/kermany_meta_mock.csv --pathologies Drusen,CNV,DME,Normal --out_dir /scratch/mock/projects/SLIViT/outputs/ --gpu 1
Num of cpus is 16
Batch size is 16
Label counts is: {'Drusen': '518 Positive Scans, 4482 Negative Scans', 'CNV': '2244 Positive Scans, 2756 Negative Scans', 'DME': '681 Positive Scans, 4319 Negative Scans', 'Normal': '1557 Positive Scans, 3443 Negative Scans'}
Some weights of ConvNextForImageClassification were not initialized from the model checkpoint at facebook/convnext-base-224 and are newly initialized because the shapes did not match:
\- classifier.weight: found shape torch.Size([1000, 1024]) in the checkpoint and torch.Size([4, 1024]) in the model instantiated
\- classifier.bias: found shape torch.Size([1000]) in the checkpoint and torch.Size([4]) in the model instantiated
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
\# of train batches is 309
\# of validation batches is 3
epoch     train_loss  valid_loss  roc_auc_score  average_precision_score  time    
Traceback (most recent call last):--------------------------------------------------------------------------------| 0.00% [0/309 00:00<?]
  File "bb_train.py", line 89, in <module>
    learner.fit_one_cycle(n_epoch=opt.n_epochs, cbs=SaveModelCallback(fname='convnext_bb_'+opt.dataset))
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/callback/schedule.py", line 119, in fit_one_cycle
    self.fit(n_epoch, cbs=ParamScheduler(scheds)+L(cbs), reset_opt=reset_opt, wd=wd, start_epoch=start_epoch)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 264, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 253, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 247, in _do_epoch
    self._do_epoch_train()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 239, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/learner.py", line 205, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/data/load.py", line 127, in __iter__
    for b in _loaders[self.fake_l.num_workers==0](self.fake_l):
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 41, in fetch
    data = next(self.dataset_iter)
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/data/load.py", line 138, in create_batches
    yield from map(self.do_batch, self.chunkify(res))
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastcore/basics.py", line 230, in chunked
    res = list(itertools.islice(it, chunk_sz))
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/data/load.py", line 168, in do_item
    try: return self.after_item(self.create_item(s))
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/fastai/data/load.py", line 175, in create_item
    if self.indexed: return self.dataset[s or 0]
  File "/scratch/mock/envs/slivit/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 391, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/scratch/mock/projects/SLIViT/Dsets/KDataset.py", line 45, in __getitem__
    sample = self.samples[idx]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by berkindurmus** [comment]
resolved
