### ISSUE TITLE
A missing package (pydicom)

### ISSUE THREAD

**Issue by orenavram** [berkindurmus/SLIViT#6]
(slivit) mock@halperingpu01:/scratch/mock/projects/SLIViT$ python slivit_train.py --dataset3d nodulemnist --task classification --bbpath outputs/convnext_bb_kermany.pth --nslc 28 --depth 5 --dim 64 --heads 20 --out_dir outputs/
Traceback (most recent call last):
  File "slivit_train.py", line 11, in <module>
    from Dsets.NDataset import NDataset
  File "/scratch/mock/projects/SLIViT/Dsets/NDataset.py", line 9, in <module>
    from utils.slivit_auxiliaries import *
  File "/scratch/mock/projects/SLIViT/utils/slivit_auxiliaries.py", line 6, in <module>
    import pydicom as dicom
ModuleNotFoundError: No module named 'pydicom'

**Comment by orenavram** [comment]
I see that the installation instructions were updated as part of fixing the previous independent issue. Thanks.
